[package]
name = "h4m"
version = "0.4.0"
edition = "2021"
description = "Dependency-free pure rust HVQM4 video and IMA audio decoder"
documentation = "https://docs.rs/h4m"
repository = "https://github.com/rowanG077/h4m-rs"
readme = "README.md"
license = "LGPL-2.0-or-later"
keywords = ["h4m", "hvqm4", "video", "decoder", "gamedev"]
categories = ["multimedia::video", "multimedia::encoding"]
include = [
  "/src/**",
  "/tests/**",
  "/benches/**",
  "/examples/**",
  "/docs/**",
  "/LICENSE.vgmstream",
  "/Cargo.toml",
  "/Cargo.lock",
  "/README.md",
  "/RELEASING.md",
  "/LICENSE",
  "/CHANGELOG.md",
]

[features]
default = ["std"]
alloc = []
std = ["alloc"]

[[bin]]
name = "h4m"
path = "src/bin/h4m.rs"
required-features = ["std"]

[[example]]
name = "audio"
test = true
required-features = ["std"]

[[bench]]
name = "decode"
harness = false
required-features = ["std"]

[profile.release]
lto = "thin"
codegen-units = 1

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
